name: EpicEnchant
version: 1.1.3
description: Upgrade your enchantments like in rpg style game. Fully configurable!
author: MatiXOR
main: pl.matix.epicenchant.EpicEnchant
api-version: 1.13
depend: [Vault]

commands:
   epicenchant: {}